### ISSUE TITLE
Feature request: add custom word list to existing word list

### ISSUE THREAD

**Issue by jakobhviid** [neilsustc/vscode-dic-completion#2]
Sometimes I have domain-specific words I have problems spelling. In these cases, it would be nice to be able to add custom words to the wordlist through visual studio code.

If you are not interested in making a feature like this, just close the issue.

Thank you for a great extension!

**Comment by neilsustc** [comment]
A good feature, I will try

**Comment by jakobhviid** [comment]
Thanks! This could help quite a bit!

**Comment by amitguptagwl** [comment]
I tried to add words to words file in `.vscode/extensions` folder. But vscode didn't pick those words. :(

**Comment by neilsustc** [comment]
Please try v0.5.0.

command `Completion: Open User Dictionary`

**Comment by amitguptagwl** [comment]
Thanks for quick update. But unfortunately It is still not picking the additional words. Moreover the command you have given is giving error "command 'completion.openUserDict' not found"

**Comment by jakobhviid** [comment]
It would be great if the words could be read from the settings file or the .vscode/customfilename.js location. The first one would add the words everywhere, where the second option would make it project specific which is actually quite useful.

**Comment by neilsustc** [comment]
@amitguptagwl Thanks, v0.5.1 should work well now 😂

@jakobhviid Yes, customable wordlist file path might be better, but I guess it is not necessary. Because we might be only interested in the word we want when typing. So it doesn't matter to have more words in the completion list.

**Comment by jakobhviid** [comment]
Works perfectly! Thanks!

**Comment by amitguptagwl** [comment]
Unfortunately not working for me. I'm on Ubuntu 17.10

**Comment by neilsustc** [comment]
@amitguptagwl Could you go to `menubar > help > toggle dev tools` and see whether there is any error message? I don't have a Ubuntu machine now.

**Comment by amitguptagwl** [comment]
I tried that option. but no error there
