### ISSUE TITLE
Stop suggesting words after some typing

### ISSUE THREAD

**Issue by junyuan-chen** [neilsustc/vscode-dic-completion#4]
The words show up in the quick suggestions normally every time I open a new tex file. However, just after typing about 10 words, the quick suggestion stops suggesting words from this extension. I tried to disable the extension and then reenable it and reboot the OS, but the same problem still exists.

I am using the latest stable version of VS Code on a Macbook Pro.

**Comment by neilsustc** [comment]
Could you provide more information such as a code snippet? I cannot reproduce on my PC.

And please navigate to menubar>help>toggle dev tools to see whether there is any error.

**Comment by junyuan-chen** [comment]
Thank you for your reply!
After I removed the setting "editor.tabCompletion": true, away from my setting for Latex, the word suggestion started to work again!

**Comment by neilsustc** [comment]
Glad to hear that 😉
