### ISSUE TITLE
command 'completion.openUserDict' not found

### ISSUE THREAD

**Issue by tecosaur** [neilsustc/vscode-dic-completion#5]
Just installed, coming across this error:

command 'completion.openUserDict' not found

(VS Code 1.25, Windows 10, large custom word file)

**Comment by neilsustc** [comment]
Could you please go to `menubar>help>toggle developer tools` to see whether there is any error message?

**Comment by tecosaur** [comment]
### Error Message

Error: command 'completion.openUserDict' not found
    at t._tryExecuteCommand (commandService.ts:57)
    at commandService.ts:50
    at n.Class.derive._oncancel.then (winjs.base.js:1581)
    at t.executeCommand (commandService.ts:50)
    at t.run (actions.ts:204)
    at t.run (actions.ts:252)
    at commandsHandler.ts:306
    at n.Class.derive._oncancel.done (winjs.base.js:1539)
    at Object.g [as _notify] (winjs.base.js:1195)
    at Object.enter (winjs.base.js:867)
    at n.Class.derive._oncancel._run (winjs.base.js:1083)
    at n.Class.derive._oncancel._completed (winjs.base.js:1051)

### And upon clicking the 'more info' arrow:

e.onDidNotificationChange | @ | notificationsAlerts.ts:40
-- | -- | --
(anonymous) | @ | notificationsAlerts.ts:28
e.fire | @ | event.ts:140
e.notify | @ | notifications.ts:127
e.error | @ | notificationService.ts:61
t.onError | @ | commandsHandler.ts:325
(anonymous) | @ | commandsHandler.ts:310
done | @ | winjs.base.js:1393
(anonymous) | @ | commandsHandler.ts:306
done | @ | winjs.base.js:1539
g | @ | winjs.base.js:1195
enter | @ | winjs.base.js:867
_run | @ | winjs.base.js:1083
_completed | @ | winjs.base.js:1051

**Comment by neilsustc** [comment]
I don't know why from the error message. Could you please try to

1. uninstall this extension
2. restart vscode
3. reinstall this extension

I guess some of the extension files are missing.

**Comment by tecosaur** [comment]
I have:
1. Clicked the uninstall button
2. Clicked the reload button
3. Found extension and clicked install button
4. Clicked reload button
5. Tried command again
Same error :(

**Comment by neilsustc** [comment]
Oh, I guess I know the reason. This extension will only be activated if you open a Markdown/LaTeX/HTML file. Try open such a file at first and then execute that `openUserDict` command.

**Comment by tecosaur** [comment]
Unfortunately, I was in a .tex file at the time, and I have also verified that it doesn't work for html.

**Comment by neilsustc** [comment]
Are word completions work well?

**Comment by tecosaur** [comment]
Standard word completions were working absolutely fine, are no longer. No idea why.

**Comment by neilsustc** [comment]
I also have no idea... 😔

Maybe you can try to install the latest build from [here](https://ci.appveyor.com/project/neilsustc/vscode-dic-completion/build/artifacts)

**Comment by tecosaur** [comment]
Sorry it's taken a while. I'll try to test this by the end of the week :)

**Comment by tecosaur** [comment]
It works!
No further issues so far :)

**Comment by tecosaur** [comment]
@yzhang-gh I'm getting this issue again :( the same presentation as previously, new computer.

**Comment by yzhang-gh** [comment]
I noticed a weird problem recently (the extension is running and `openUserDict` also works, but no completion at all). I suspect the Settings Sync extension did something wrong.

However, reinstalling this extension solved my problem. I would suggest reinstalling it and see whether it is still broken.

**Comment by tecosaur** [comment]
I haven't got the settings sync extension, so I don't think that has anything to do with my particular case, and I've reinstalled it and unfortunately that hasn't helped. Even disabling all other extensions didnt.

**Comment by yzhang-gh** [comment]
Could you run `show running extensions` in the command palette to see whether this extension is activated?

And please also check the developer console in case there is some useful information.
