### ISSUE TITLE
Least Num Of Chars

### ISSUE THREAD

**Issue by tecosaur** [neilsustc/vscode-dic-completion#7]
I've set least num of chars to 3, however, I still get suggestions after 2 letters. Any sugestions?

**Comment by neilsustc** [comment]
I guess those are suggestions based on your document (provided by vscode) instead of the dictionary (this extension)

**Comment by tecosaur** [comment]
Not so sure about that
![image](https://user-images.githubusercontent.com/20903656/45747290-f0901e00-bc37-11e8-84f7-f25bed651e71.png)

**Comment by neilsustc** [comment]
Normally `s` has these suggestions

![image](https://user-images.githubusercontent.com/7588612/45747521-fc5eee80-bbfd-11e8-98ca-351c1024efa0.png)

For `scr`

![image](https://user-images.githubusercontent.com/7588612/45747552-100a5500-bbfe-11e8-804e-59b07dfef0d0.png)

which are far more than what you get.

Your suggestions are words that ever in your document. This is provided by the vscode and it doesn't have a `leastNumOfChar` option.

**Comment by tecosaur** [comment]
Sorry about that, didn't recognise quite a few of the words and assumes it muct have been this.
Thanks for the speedy reply :)

**Comment by neilsustc** [comment]
I occasionally found an `editor.wordBasedSuggestions` option (defaults to `true`)
