### ISSUE TITLE
Idea: Only have root words in word file

### ISSUE THREAD

**Issue by tecosaur** [neilsustc/vscode-dic-completion#8]
Due to the way this extension completes works, it may be worth removing words which differ only be a short suffix (such as plurals, etc.). Explanation/example below
- When `chal-` is typed,
- `challenge` and `challenger` will both be suggested
- Upon selecting `challenge` no space will be added
- So if one wanted `challenger`, one could just select `challenge` and press the key `r`
- This has the same effect as using arrow keys to select `challenger` but has two main advantages
  - (Minor) this method usually will be faster to do, since `r` sits closer to where the fingers naturally lie than the arrow keys, this holds true for other suffixes
  - (Major) by not suggesting `challenge` and `challenger`
    - Space is saved on the suggestions box
    - This opens up room for more (different) suggestions, increasing the chance that the desired word will be shown
    - Potentially makes the suggestion box look less cluttered / stuffed full of words

Bonus idea (significant undertaking): Making it so that if a word that has multiple possible suffixes is selected, new suggestions for the suffixes appear.

**Comment by neilsustc** [comment]
Do you know you can even type `chalr` (`chal` and then `r`) to get `challenger` 😏

![image](https://user-images.githubusercontent.com/7588612/46257207-ec70c580-c4ad-11e8-8008-c099abca2b47.png)

And another possible reason is the irregular words, e.g. `try` and `tries`.

**Comment by tecosaur** [comment]
Aaah, that's quite nice :) Since now the work doesn't seem to have sufficient benefit to warrant it lets close this issue.
